language: java

os: linux
dist: trusty
jdk: oraclejdk8

sudo: required
services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./gradlew clean
  - ./gradlew -p ./monolithic/ui packageToContainer

script:
  - docker pull zutherb/monolithic-shop
  - docker tag zutherb/monolithic-shop:latest $DOCKER_USERNAME/monolithic-shop:latest
  - docker push $DOCKER_USERNAME/monolithic-shop:latest